In [1]:
import warnings
warnings.filterwarnings("ignore")
import os
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from xgboost import XGBClassifier

from cpcv_analysis.config import XGB_PARAMS, ASSETS, TIMELINES, SYNTHETIC_SCENARIOS, TIMELINE_B
from cpcv_analysis.experiment import run_experiment, _run_experiment_from_arrays
from cpcv_analysis.synthetic import generate_synthetic_prices
from cpcv_analysis.data import build_features

clf_template = XGBClassifier(**XGB_PARAMS)
METHODS = ["cpcv", "wf", "kfold"]
ASSET_TICKERS = list(ASSETS.keys())

os.makedirs("plots", exist_ok=True)
os.makedirs("results", exist_ok=True)
print(f"Assets: {ASSET_TICKERS}")
print(f"Timelines: {[t['name'] for t in TIMELINES]}")
print(f"Methods: {METHODS}")

Assets: ['SPY', 'AAPL', 'IWM', 'BTC-USD']
Timelines: ['2023-2026', 'COVID-2017-2020']
Methods: ['cpcv', 'wf', 'kfold']

In [2]:
real_rows = []

for timeline_cfg in TIMELINES:
    for ticker in ASSET_TICKERS:
        for method in METHODS:
            print(f"Running: {timeline_cfg['name']} | {ticker} | {method}...")
            try:
                metrics, fig = run_experiment(ticker, timeline_cfg, clf_template, method=method)
                fname = f"plots/real_{timeline_cfg['name']}_{ticker}_{method}.png"
                fig.savefig(fname, dpi=100, bbox_inches="tight")
                plt.close(fig)
                row = dict(timeline=timeline_cfg["name"], asset=ticker, method=method, **metrics)
                real_rows.append(row)
                print(f"  -> delta_median={metrics['delta_median']:.3f}, coverage_90={metrics['coverage_90']}")
            except Exception as e:
                print(f"  ERROR: {e}")
                import traceback; traceback.print_exc()

real_df = pd.DataFrame(real_rows)
real_df.to_csv("results/real_experiments.csv", index=False)
print(f"\nCompleted {len(real_rows)} real experiments")
real_df

Running: 2023-2026 | SPY | cpcv...

[data] Downloaded SPY prices and cached → /Users/jeronimo.deli/Desktop/other/Vs/TSP/CPCV_tesis/cpcv_analysis/../data_cache/SPY_2023-05-01_2026-01-01.csv
[data] Observations: 646  |  Class balance: 64.1% up
[data] Feature shape: (646, 6)  |  Date range: 2023-05-30 → 2025-12-23

Val SRs:        ['2.110', '1.521', '2.549', '2.762', '2.869']
Mediana val:    2.549
Hold-out SR:    0.945
[P5, P95]:      [1.639, 2.847]
Cobertura:      fuera IC
  -> delta_median=1.604, coverage_90=0
Running: 2023-2026 | SPY | wf...
[data] Loaded SPY prices from cache → /Users/jeronimo.deli/Desktop/other/Vs/TSP/CPCV_tesis/cpcv_analysis/../data_cache/SPY_2023-05-01_2026-01-01.csv
[data] Observations: 646  |  Class balance: 64.1% up
[data] Feature shape: (646, 6)  |  Date range: 2023-05-30 → 2025-12-23

Val SRs:        ['3.484', '2.583']
Mediana val:    3.034
Hold-out SR:    0.945
[P5, P95]:      [2.628, 3.439]
Cobertura:      fuera IC
  -> delta_median=2.088, coverage_90=0
Running: 2023-2026 | SPY | kfold...
[data] Loaded SPY prices from cache → /Users/jeronimo.deli/Desktop/other/Vs/TSP/CPCV_tesis/cpcv_analysis/../data_cache/SPY_2023-05-01_2026-01-01.csv
[data] Observations: 646  |  Class balance: 64.1% up
[data] Feature shape: (646, 6)  |  Date range: 2023-05-30 → 2025-12-23

Val SRs:        ['0.869', '13.282', '-1.025', '7.402', '2.731']
Mediana val:    2.731
Hold-out SR:    0.945
[P5, P95]:      [-0.646, 12.106]
Cobertura:      dentro IC
  -> delta_median=1.786, coverage_90=1
Running: 2023-2026 | AAPL | cpcv...

[data] Downloaded AAPL prices and cached → /Users/jeronimo.deli/Desktop/other/Vs/TSP/CPCV_tesis/cpcv_analysis/../data_cache/AAPL_2023-05-01_2026-01-01.csv
[data] Observations: 646  |  Class balance: 55.6% up
[data] Feature shape: (646, 6)  |  Date range: 2023-05-30 → 2025-12-23

Val SRs:        ['-2.085', '-2.658', '-2.173', '-3.833', '-1.441']
Mediana val:    -2.173
Hold-out SR:    0.850
[P5, P95]:      [-3.598, -1.570]
Cobertura:      fuera IC
  -> delta_median=-3.022, coverage_90=0
Running: 2023-2026 | AAPL | wf...
[data] Loaded AAPL prices from cache → /Users/jeronimo.deli/Desktop/other/Vs/TSP/CPCV_tesis/cpcv_analysis/../data_cache/AAPL_2023-05-01_2026-01-01.csv
[data] Observations: 646  |  Class balance: 55.6% up
[data] Feature shape: (646, 6)  |  Date range: 2023-05-30 → 2025-12-23

Val SRs:        ['-3.672', '3.042']
Mediana val:    -0.315
Hold-out SR:    0.850
[P5, P95]:      [-3.336, 2.706]
Cobertura:      dentro IC
  -> delta_median=-1.164, coverage_90=1
Running: 2023-2026 | AAPL | kfold...
[data] Loaded AAPL prices from cache → /Users/jeronimo.deli/Desktop/other/Vs/TSP/CPCV_tesis/cpcv_analysis/../data_cache/AAPL_2023-05-01_2026-01-01.csv
[data] Observations: 646  |  Class balance: 55.6% up
[data] Feature shape: (646, 6)  |  Date range: 2023-05-30 → 2025-12-23

Val SRs:        ['-0.291', '-12.801', '-1.641', '-1.267', '-1.364']
Mediana val:    -1.364
Hold-out SR:    0.850
[P5, P95]:      [-10.569, -0.486]
Cobertura:      fuera IC
  -> delta_median=-2.214, coverage_90=0
Running: 2023-2026 | IWM | cpcv...

[data] Downloaded IWM prices and cached → /Users/jeronimo.deli/Desktop/other/Vs/TSP/CPCV_tesis/cpcv_analysis/../data_cache/IWM_2023-05-01_2026-01-01.csv
[data] Observations: 646  |  Class balance: 54.3% up
[data] Feature shape: (646, 6)  |  Date range: 2023-05-30 → 2025-12-23

Val SRs:        ['1.538', '1.965', '1.614', '1.104', '0.888']
Mediana val:    1.538
Hold-out SR:    1.649
[P5, P95]:      [0.931, 1.895]
Cobertura:      dentro IC
  -> delta_median=-0.111, coverage_90=1
Running: 2023-2026 | IWM | wf...
[data] Loaded IWM prices from cache → /Users/jeronimo.deli/Desktop/other/Vs/TSP/CPCV_tesis/cpcv_analysis/../data_cache/IWM_2023-05-01_2026-01-01.csv
[data] Observations: 646  |  Class balance: 54.3% up
[data] Feature shape: (646, 6)  |  Date range: 2023-05-30 → 2025-12-23

Val SRs:        ['4.402', '-1.402']
Mediana val:    1.500
Hold-out SR:    1.649
[P5, P95]:      [-1.111, 4.111]
Cobertura:      dentro IC
  -> delta_median=-0.149, coverage_90=1
Running: 2023-2026 | IWM | kfold...
[data] Loaded IWM prices from cache → /Users/jeronimo.deli/Desktop/other/Vs/TSP/CPCV_tesis/cpcv_analysis/../data_cache/IWM_2023-05-01_2026-01-01.csv
[data] Observations: 646  |  Class balance: 54.3% up
[data] Feature shape: (646, 6)  |  Date range: 2023-05-30 → 2025-12-23

Val SRs:        ['-2.511', '-2.788', '2.365', '-1.814', '3.003']
Mediana val:    -1.814
Hold-out SR:    1.649
[P5, P95]:      [-2.733, 2.875]
Cobertura:      dentro IC
  -> delta_median=-3.462, coverage_90=1
Running: 2023-2026 | BTC-USD | cpcv...

[data] Downloaded BTC-USD prices and cached → /Users/jeronimo.deli/Desktop/other/Vs/TSP/CPCV_tesis/cpcv_analysis/../data_cache/BTC-USD_2023-05-01_2026-01-01.csv
[data] Observations: 951  |  Class balance: 53.9% up
[data] Feature shape: (951, 6)  |  Date range: 2023-05-21 → 2025-12-26

Val SRs:        ['-1.418', '0.916', '2.214', '-1.522', '-0.574']
Mediana val:    -0.574
Hold-out SR:    1.934
[P5, P95]:      [-1.501, 1.955]
Cobertura:      dentro IC
  -> delta_median=-2.508, coverage_90=1
Running: 2023-2026 | BTC-USD | wf...
[data] Loaded BTC-USD prices from cache → /Users/jeronimo.deli/Desktop/other/Vs/TSP/CPCV_tesis/cpcv_analysis/../data_cache/BTC-USD_2023-05-01_2026-01-01.csv
[data] Observations: 951  |  Class balance: 53.9% up
[data] Feature shape: (951, 6)  |  Date range: 2023-05-21 → 2025-12-26

Val SRs:        ['-1.387', '-0.174']
Mediana val:    -0.781
Hold-out SR:    1.934
[P5, P95]:      [-1.327, -0.235]
Cobertura:      fuera IC
  -> delta_median=-2.715, coverage_90=0
Running: 2023-2026 | BTC-USD | kfold...
[data] Loaded BTC-USD prices from cache → /Users/jeronimo.deli/Desktop/other/Vs/TSP/CPCV_tesis/cpcv_analysis/../data_cache/BTC-USD_2023-05-01_2026-01-01.csv
[data] Observations: 951  |  Class balance: 53.9% up
[data] Feature shape: (951, 6)  |  Date range: 2023-05-21 → 2025-12-26

Val SRs:        ['2.080', '-7.457', '4.498', '-3.136', '5.135']
Mediana val:    2.080
Hold-out SR:    1.934
[P5, P95]:      [-6.593, 5.007]
Cobertura:      dentro IC
  -> delta_median=0.146, coverage_90=1
Running: COVID-2017-2020 | SPY | cpcv...

[data] Downloaded SPY prices and cached → /Users/jeronimo.deli/Desktop/other/Vs/TSP/CPCV_tesis/cpcv_analysis/../data_cache/SPY_2017-05-01_2020-05-01.csv
[data] Observations: 731  |  Class balance: 64.2% up
[data] Feature shape: (731, 6)  |  Date range: 2017-05-30 → 2020-04-23

Val SRs:        ['1.756', '1.355', '-0.266', '-0.088', '1.866']
Mediana val:    1.355
Hold-out SR:    -2.426
[P5, P95]:      [-0.231, 1.844]
Cobertura:      fuera IC
  -> delta_median=3.781, coverage_90=0
Running: COVID-2017-2020 | SPY | wf...
[data] Loaded SPY prices from cache → /Users/jeronimo.deli/Desktop/other/Vs/TSP/CPCV_tesis/cpcv_analysis/../data_cache/SPY_2017-05-01_2020-05-01.csv
[data] Observations: 731  |  Class balance: 64.2% up
[data] Feature shape: (731, 6)  |  Date range: 2017-05-30 → 2020-04-23

Val SRs:        ['2.655', '0.750']
Mediana val:    1.703
Hold-out SR:    -2.426
[P5, P95]:      [0.846, 2.559]
Cobertura:      fuera IC
  -> delta_median=4.129, coverage_90=0
Running: COVID-2017-2020 | SPY | kfold...
[data] Loaded SPY prices from cache → /Users/jeronimo.deli/Desktop/other/Vs/TSP/CPCV_tesis/cpcv_analysis/../data_cache/SPY_2017-05-01_2020-05-01.csv
[data] Observations: 731  |  Class balance: 64.2% up
[data] Feature shape: (731, 6)  |  Date range: 2017-05-30 → 2020-04-23

Val SRs:        ['3.571', '-2.802', '4.803', '4.784', '-1.155']
Mediana val:    3.571
Hold-out SR:    -2.426
[P5, P95]:      [-2.473, 4.799]
Cobertura:      dentro IC
  -> delta_median=5.997, coverage_90=1
Running: COVID-2017-2020 | AAPL | cpcv...

[data] Downloaded AAPL prices and cached → /Users/jeronimo.deli/Desktop/other/Vs/TSP/CPCV_tesis/cpcv_analysis/../data_cache/AAPL_2017-05-01_2020-05-01.csv
[data] Observations: 731  |  Class balance: 62.1% up
[data] Feature shape: (731, 6)  |  Date range: 2017-05-30 → 2020-04-23

Val SRs:        ['-3.996', '-1.070', '-0.301', '-2.341', '-0.388']
Mediana val:    -1.070
Hold-out SR:    -0.736
[P5, P95]:      [-3.665, -0.318]
Cobertura:      dentro IC
  -> delta_median=-0.334, coverage_90=1
Running: COVID-2017-2020 | AAPL | wf...
[data] Loaded AAPL prices from cache → /Users/jeronimo.deli/Desktop/other/Vs/TSP/CPCV_tesis/cpcv_analysis/../data_cache/AAPL_2017-05-01_2020-05-01.csv
[data] Observations: 731  |  Class balance: 62.1% up
[data] Feature shape: (731, 6)  |  Date range: 2017-05-30 → 2020-04-23

Val SRs:        ['-11.661', '0.476']
Mediana val:    -5.592
Hold-out SR:    -0.736
[P5, P95]:      [-11.054, -0.131]
Cobertura:      dentro IC
  -> delta_median=-4.857, coverage_90=1
Running: COVID-2017-2020 | AAPL | kfold...
[data] Loaded AAPL prices from cache → /Users/jeronimo.deli/Desktop/other/Vs/TSP/CPCV_tesis/cpcv_analysis/../data_cache/AAPL_2017-05-01_2020-05-01.csv
[data] Observations: 731  |  Class balance: 62.1% up
[data] Feature shape: (731, 6)  |  Date range: 2017-05-30 → 2020-04-23

Val SRs:        ['12.362', '-10.682', '3.432', '-1.404', '-3.391']
Mediana val:    -1.404
Hold-out SR:    -0.736
[P5, P95]:      [-9.224, 10.576]
Cobertura:      dentro IC
  -> delta_median=-0.668, coverage_90=1
Running: COVID-2017-2020 | IWM | cpcv...

[data] Downloaded IWM prices and cached → /Users/jeronimo.deli/Desktop/other/Vs/TSP/CPCV_tesis/cpcv_analysis/../data_cache/IWM_2017-05-01_2020-05-01.csv
[data] Observations: 731  |  Class balance: 54.9% up
[data] Feature shape: (731, 6)  |  Date range: 2017-05-30 → 2020-04-23

Val SRs:        ['-2.357', '-3.503', '-1.583', '-1.431', '-3.328']
Mediana val:    -2.357
Hold-out SR:    -2.747
[P5, P95]:      [-3.468, -1.461]
Cobertura:      dentro IC
  -> delta_median=0.390, coverage_90=1
Running: COVID-2017-2020 | IWM | wf...
[data] Loaded IWM prices from cache → /Users/jeronimo.deli/Desktop/other/Vs/TSP/CPCV_tesis/cpcv_analysis/../data_cache/IWM_2017-05-01_2020-05-01.csv
[data] Observations: 731  |  Class balance: 54.9% up
[data] Feature shape: (731, 6)  |  Date range: 2017-05-30 → 2020-04-23

Val SRs:        ['-4.207', '-2.384']
Mediana val:    -3.295
Hold-out SR:    -2.747
[P5, P95]:      [-4.116, -2.475]
Cobertura:      dentro IC
  -> delta_median=-0.549, coverage_90=1
Running: COVID-2017-2020 | IWM | kfold...
[data] Loaded IWM prices from cache → /Users/jeronimo.deli/Desktop/other/Vs/TSP/CPCV_tesis/cpcv_analysis/../data_cache/IWM_2017-05-01_2020-05-01.csv
[data] Observations: 731  |  Class balance: 54.9% up
[data] Feature shape: (731, 6)  |  Date range: 2017-05-30 → 2020-04-23

Val SRs:        ['3.894', '-8.467', '-0.623', '0.190', '-0.372']
Mediana val:    -0.372
Hold-out SR:    -2.747
[P5, P95]:      [-6.898, 3.153]
Cobertura:      dentro IC
  -> delta_median=2.375, coverage_90=1
Running: COVID-2017-2020 | BTC-USD | cpcv...

[data] Downloaded BTC-USD prices and cached → /Users/jeronimo.deli/Desktop/other/Vs/TSP/CPCV_tesis/cpcv_analysis/../data_cache/BTC-USD_2017-05-01_2020-05-01.csv
[data] Observations: 1071  |  Class balance: 53.4% up
[data] Feature shape: (1071, 6)  |  Date range: 2017-05-21 → 2020-04-25

Val SRs:        ['-4.233', '-4.048', '-2.983', '-2.095', '-5.329']
Mediana val:    -4.048
Hold-out SR:    -0.849
[P5, P95]:      [-5.110, -2.273]
Cobertura:      fuera IC
  -> delta_median=-3.199, coverage_90=0
Running: COVID-2017-2020 | BTC-USD | wf...
[data] Loaded BTC-USD prices from cache → /Users/jeronimo.deli/Desktop/other/Vs/TSP/CPCV_tesis/cpcv_analysis/../data_cache/BTC-USD_2017-05-01_2020-05-01.csv
[data] Observations: 1071  |  Class balance: 53.4% up
[data] Feature shape: (1071, 6)  |  Date range: 2017-05-21 → 2020-04-25

Val SRs:        ['-3.442', '0.735']
Mediana val:    -1.354
Hold-out SR:    -0.849
[P5, P95]:      [-3.233, 0.526]
Cobertura:      dentro IC
  -> delta_median=-0.504, coverage_90=1
Running: COVID-2017-2020 | BTC-USD | kfold...
[data] Loaded BTC-USD prices from cache → /Users/jeronimo.deli/Desktop/other/Vs/TSP/CPCV_tesis/cpcv_analysis/../data_cache/BTC-USD_2017-05-01_2020-05-01.csv
[data] Observations: 1071  |  Class balance: 53.4% up
[data] Feature shape: (1071, 6)  |  Date range: 2017-05-21 → 2020-04-25

Val SRs:        ['-2.396', '2.513', '-9.127', '-7.562', '0.198']
Mediana val:    -2.396
Hold-out SR:    -0.849
[P5, P95]:      [-8.814, 2.050]
Cobertura:      dentro IC
  -> delta_median=-1.546, coverage_90=1

Completed 24 real experiments

,timeline,asset,method,delta_median,coverage_90,rank_pct,dispersion,delta_maxDD,pct_positive
0,2023-2026,SPY,cpcv,1.604059,0,0.0,0.494423,-0.146693,1.0
1,2023-2026,SPY,wf,2.088433,0,0.0,0.450153,0.018513,1.0
2,2023-2026,SPY,kfold,1.785565,1,0.4,5.143395,-0.024489,0.8
3,2023-2026,AAPL,cpcv,-3.022427,0,1.0,0.797948,-1.116549,0.0
4,2023-2026,AAPL,wf,-1.164274,1,0.5,3.356836,-0.998752,0.5
5,2023-2026,AAPL,kfold,-2.213721,0,1.0,4.686517,-1.657106,0.0
6,2023-2026,IWM,cpcv,-0.111016,1,0.8,0.382312,-0.025103,1.0
7,2023-2026,IWM,wf,-0.148622,1,0.5,2.901554,-0.389705,0.5
8,2023-2026,IWM,kfold,-3.462283,1,0.6,2.504839,-0.447120,0.4
9,2023-2026,BTC-USD,cpcv,-2.508164,1,0.8,1.440239,-0.905531,0.4
10,2023-2026,BTC-USD,wf,-2.714594,0,1.0,0.606499,-1.376143,0.0
11,2023-2026,BTC-USD,kfold,0.146437,1,0.4,4.818995,-1.050091,0.6
12,COVID-2017-2020,SPY,cpcv,3.780716,0,0.0,0.917104,1.231430,0.6
13,COVID-2017-2020,SPY,wf,4.128809,0,0.0,0.952109,1.544513,1.0
14,COVID-2017-2020,SPY,kfold,5.997369,1,0.2,3.192653,1.424081,0.6
15,COVID-2017-2020,AAPL,cpcv,-0.334326,1,0.6,1.394915,0.078229,0.0
16,COVID-2017-2020,AAPL,wf,-4.856785,1,0.5,6.068682,-0.963829,0.5
17,COVID-2017-2020,AAPL,kfold,-0.668479,1,0.6,7.643866,0.488143,0.4
18,COVID-2017-2020,IWM,cpcv,0.390067,1,0.4,0.857663,-0.030492,0.0
19,COVID-2017-2020,IWM,wf,-0.548519,1,0.5,0.911310,0.277412,0.0
20,COVID-2017-2020,IWM,kfold,2.374513,1,0.2,4.040495,0.258989,0.4
21,COVID-2017-2020,BTC-USD,cpcv,-3.198995,0,1.0,1.108397,-5.678059,0.0
22,COVID-2017-2020,BTC-USD,wf,-0.504230,1,0.5,2.088269,-1.350295,0.5
23,COVID-2017-2020,BTC-USD,kfold,-1.546381,1,0.6,4.448766,-4.825091,0.4

In [3]:
display_cols = ["timeline", "asset", "method",
                "delta_median", "coverage_90", "rank_pct",
                "dispersion", "delta_maxDD", "pct_positive"]
real_df[display_cols].round(4)

,timeline,asset,method,delta_median,coverage_90,rank_pct,dispersion,delta_maxDD,pct_positive
0,2023-2026,SPY,cpcv,1.6041,0,0.0,0.4944,-0.1467,1.0
1,2023-2026,SPY,wf,2.0884,0,0.0,0.4502,0.0185,1.0
2,2023-2026,SPY,kfold,1.7856,1,0.4,5.1434,-0.0245,0.8
3,2023-2026,AAPL,cpcv,-3.0224,0,1.0,0.7979,-1.1165,0.0
4,2023-2026,AAPL,wf,-1.1643,1,0.5,3.3568,-0.9988,0.5
5,2023-2026,AAPL,kfold,-2.2137,0,1.0,4.6865,-1.6571,0.0
6,2023-2026,IWM,cpcv,-0.1110,1,0.8,0.3823,-0.0251,1.0
7,2023-2026,IWM,wf,-0.1486,1,0.5,2.9016,-0.3897,0.5
8,2023-2026,IWM,kfold,-3.4623,1,0.6,2.5048,-0.4471,0.4
9,2023-2026,BTC-USD,cpcv,-2.5082,1,0.8,1.4402,-0.9055,0.4
10,2023-2026,BTC-USD,wf,-2.7146,0,1.0,0.6065,-1.3761,0.0
11,2023-2026,BTC-USD,kfold,0.1464,1,0.4,4.8190,-1.0501,0.6
12,COVID-2017-2020,SPY,cpcv,3.7807,0,0.0,0.9171,1.2314,0.6
13,COVID-2017-2020,SPY,wf,4.1288,0,0.0,0.9521,1.5445,1.0
14,COVID-2017-2020,SPY,kfold,5.9974,1,0.2,3.1927,1.4241,0.6
15,COVID-2017-2020,AAPL,cpcv,-0.3343,1,0.6,1.3949,0.0782,0.0
16,COVID-2017-2020,AAPL,wf,-4.8568,1,0.5,6.0687,-0.9638,0.5
17,COVID-2017-2020,AAPL,kfold,-0.6685,1,0.6,7.6439,0.4881,0.4
18,COVID-2017-2020,IWM,cpcv,0.3901,1,0.4,0.8577,-0.0305,0.0
19,COVID-2017-2020,IWM,wf,-0.5485,1,0.5,0.9113,0.2774,0.0
20,COVID-2017-2020,IWM,kfold,2.3745,1,0.2,4.0405,0.2590,0.4
21,COVID-2017-2020,BTC-USD,cpcv,-3.1990,0,1.0,1.1084,-5.6781,0.0
22,COVID-2017-2020,BTC-USD,wf,-0.5042,1,0.5,2.0883,-1.3503,0.5
23,COVID-2017-2020,BTC-USD,kfold,-1.5464,1,0.6,4.4488,-4.8251,0.4

In [4]:
synth_rows = []

for scenario in SYNTHETIC_SCENARIOS:
    seed = int(scenario["id"])
    prices_synth = generate_synthetic_prices(scenario, seed=seed)
    X_s, y_s, t1_s, _, fwd_ret_s = build_features(prices_synth)

    timeline_synth = dict(
        name=f"synth_{scenario['id']}",
        wf_start=TIMELINE_B["wf_start"],
        dev_start=TIMELINE_B["dev_start"],
        dev_end=TIMELINE_B["dev_end"],
        retrain_start=TIMELINE_B["retrain_start"],
        retrain_end=TIMELINE_B["retrain_end"],
        holdout_start=TIMELINE_B["holdout_start"],
        holdout_end=TIMELINE_B["holdout_end"],
        download_start=TIMELINE_B["download_start"],
        download_end=TIMELINE_B["download_end"],
    )

    for method in METHODS:
        print(f"Synthetic {scenario['id']} {scenario['name']} | {method}...")
        try:
            metrics, fig = _run_experiment_from_arrays(
                X_s, y_s, t1_s, prices_synth, fwd_ret_s,
                timeline_synth, clf_template, method=method)
            fname = f"plots/synth_{scenario['id']}_{scenario['name']}_{method}.png"
            fig.savefig(fname, dpi=100, bbox_inches="tight")
            plt.close(fig)
            row = dict(scenario_id=scenario["id"], scenario_name=scenario["name"], method=method, **metrics)
            synth_rows.append(row)
            print(f"  -> delta_median={metrics['delta_median']:.3f}")
        except Exception as e:
            print(f"  ERROR: {e}")
            import traceback; traceback.print_exc()

synth_df = pd.DataFrame(synth_rows)
synth_df.to_csv("results/synthetic_experiments.csv", index=False)
print(f"\nCompleted {len(synth_rows)} synthetic experiments")

[data] Observations: 410  |  Class balance: 47.1% up
[data] Feature shape: (410, 6)  |  Date range: 2018-10-01 → 2020-04-24
Synthetic 01 bull_bull_bull | cpcv...

Val SRs:        ['3.449', '3.749', '4.440', '4.444', '2.204']
Mediana val:    3.749
Hold-out SR:    -5.637
[P5, P95]:      [2.453, 4.444]
Cobertura:      fuera IC
  -> delta_median=9.387
Synthetic 01 bull_bull_bull | wf...

Val SRs:        ['5.736', '-1.162']
Mediana val:    2.287
Hold-out SR:    -5.637
[P5, P95]:      [-0.817, 5.391]
Cobertura:      fuera IC
  -> delta_median=7.924
Synthetic 01 bull_bull_bull | kfold...

Val SRs:        ['13.885', '-0.814', '3.576', '1.025', '1.303']
Mediana val:    1.303
Hold-out SR:    -5.637
[P5, P95]:      [-0.446, 11.823]
Cobertura:      fuera IC
  -> delta_median=6.941
[data] Observations: 410  |  Class balance: 41.5% up
[data] Feature shape: (410, 6)  |  Date range: 2018-10-01 → 2020-04-24
Synthetic 02 bear_bear_bear | cpcv...

Val SRs:        ['2.646', '-0.309', '1.067', '-0.975', '0.800']
Mediana val:    0.800
Hold-out SR:    1.284
[P5, P95]:      [-0.841, 2.330]
Cobertura:      dentro IC
  -> delta_median=-0.484
Synthetic 02 bear_bear_bear | wf...

Val SRs:        ['0.407', '0.427']
Mediana val:    0.417
Hold-out SR:    1.284
[P5, P95]:      [0.408, 0.426]
Cobertura:      fuera IC
  -> delta_median=-0.867
Synthetic 02 bear_bear_bear | kfold...

Val SRs:        ['-9.498', '-0.676', '3.405', '2.237', '-2.466']
Mediana val:    -0.676
Hold-out SR:    1.284
[P5, P95]:      [-8.091, 3.171]
Cobertura:      dentro IC
  -> delta_median=-1.960
[data] Observations: 410  |  Class balance: 55.1% up
[data] Feature shape: (410, 6)  |  Date range: 2018-10-01 → 2020-04-24
Synthetic 03 stagnant_all | cpcv...

Val SRs:        ['-1.820', '-1.480', '0.764', '-1.028', '0.894']
Mediana val:    -1.028
Hold-out SR:    1.595
[P5, P95]:      [-1.752, 0.868]
Cobertura:      fuera IC
  -> delta_median=-2.622
Synthetic 03 stagnant_all | wf...

Val SRs:        ['0.023', '-3.728']
Mediana val:    -1.852
Hold-out SR:    1.595
[P5, P95]:      [-3.540, -0.164]
Cobertura:      fuera IC
  -> delta_median=-3.447
Synthetic 03 stagnant_all | kfold...

Val SRs:        ['3.645', '-8.940', '-1.819', '1.162', '-6.518']
Mediana val:    -1.819
Hold-out SR:    1.595
[P5, P95]:      [-8.456, 3.149]
Cobertura:      dentro IC
  -> delta_median=-3.414
[data] Observations: 410  |  Class balance: 58.8% up
[data] Feature shape: (410, 6)  |  Date range: 2018-10-01 → 2020-04-24
Synthetic 04 crash_in_dev_start | cpcv...

Val SRs:        ['4.167', '4.589', '5.219', '3.861', '5.048']
Mediana val:    4.589
Hold-out SR:    -3.512
[P5, P95]:      [3.922, 5.185]
Cobertura:      fuera IC
  -> delta_median=8.101
Synthetic 04 crash_in_dev_start | wf...

Val SRs:        ['2.371', '8.024']
Mediana val:    5.198
Hold-out SR:    -3.512
[P5, P95]:      [2.654, 7.741]
Cobertura:      fuera IC
  -> delta_median=8.710
Synthetic 04 crash_in_dev_start | kfold...

Val SRs:        ['2.434', '2.221', '7.719', '5.534', '9.836']
Mediana val:    5.534
Hold-out SR:    -3.512
[P5, P95]:      [2.264, 9.413]
Cobertura:      fuera IC
  -> delta_median=9.047
[data] Observations: 410  |  Class balance: 50.7% up
[data] Feature shape: (410, 6)  |  Date range: 2018-10-01 → 2020-04-24
Synthetic 05 crash_in_dev_end | cpcv...

Val SRs:        ['-1.819', '-2.453', '-0.749', '-0.954', '-0.630']
Mediana val:    -0.954
Hold-out SR:    -3.474
[P5, P95]:      [-2.326, -0.654]
Cobertura:      fuera IC
  -> delta_median=2.519
Synthetic 05 crash_in_dev_end | wf...

Val SRs:        ['-6.896', '1.896']
Mediana val:    -2.500
Hold-out SR:    -3.474
[P5, P95]:      [-6.456, 1.456]
Cobertura:      dentro IC
  -> delta_median=0.974
Synthetic 05 crash_in_dev_end | kfold...

Val SRs:        ['12.510', '-21.141', '0.669', '1.928', '-3.382']
Mediana val:    0.669
Hold-out SR:    -3.474
[P5, P95]:      [-17.589, 10.394]
Cobertura:      dentro IC
  -> delta_median=4.142
[data] Observations: 410  |  Class balance: 51.5% up
[data] Feature shape: (410, 6)  |  Date range: 2018-10-01 → 2020-04-24
Synthetic 06 crash_in_retrain | cpcv...

Val SRs:        ['-1.558', '-0.570', '-2.918', '-2.406', '-1.642']
Mediana val:    -1.642
Hold-out SR:    2.413
[P5, P95]:      [-2.816, -0.768]
Cobertura:      fuera IC
  -> delta_median=-4.055
Synthetic 06 crash_in_retrain | wf...

Val SRs:        ['0.737', '0.384']
Mediana val:    0.561
Hold-out SR:    2.413
[P5, P95]:      [0.402, 0.719]
Cobertura:      fuera IC
  -> delta_median=-1.852
Synthetic 06 crash_in_retrain | kfold...

Val SRs:        ['-3.947', '1.547', '1.563', '-1.830', '1.853']
Mediana val:    1.547
Hold-out SR:    2.413
[P5, P95]:      [-3.523, 1.795]
Cobertura:      fuera IC
  -> delta_median=-0.866
[data] Observations: 410  |  Class balance: 46.8% up
[data] Feature shape: (410, 6)  |  Date range: 2018-10-01 → 2020-04-24
Synthetic 07 crash_in_holdout_start | cpcv...

Val SRs:        ['-2.209', '-3.971', '1.069', '-1.947', '-4.535']
Mediana val:    -2.209
Hold-out SR:    -2.481
[P5, P95]:      [-4.422, 0.466]
Cobertura:      dentro IC
  -> delta_median=0.272
Synthetic 07 crash_in_holdout_start | wf...

Val SRs:        ['0.231', '0.333']
Mediana val:    0.282
Hold-out SR:    -2.481
[P5, P95]:      [0.236, 0.328]
Cobertura:      fuera IC
  -> delta_median=2.763
Synthetic 07 crash_in_holdout_start | kfold...

Val SRs:        ['-3.098', '-6.061', '-7.203', '-4.232', '-2.494']
Mediana val:    -4.232
Hold-out SR:    -2.481
[P5, P95]:      [-6.975, -2.615]
Cobertura:      fuera IC
  -> delta_median=-1.751
[data] Observations: 410  |  Class balance: 53.9% up
[data] Feature shape: (410, 6)  |  Date range: 2018-10-01 → 2020-04-24
Synthetic 08 crash_in_holdout_end | cpcv...

Val SRs:        ['-0.490', '0.684', '-1.464', '-1.123', '-1.171']
Mediana val:    -1.123
Hold-out SR:    -1.235
[P5, P95]:      [-1.405, 0.449]
Cobertura:      dentro IC
  -> delta_median=0.111
Synthetic 08 crash_in_holdout_end | wf...

Val SRs:        ['0.914', '4.921']
Mediana val:    2.918
Hold-out SR:    -1.235
[P5, P95]:      [1.115, 4.720]
Cobertura:      fuera IC
  -> delta_median=4.152
Synthetic 08 crash_in_holdout_end | kfold...

Val SRs:        ['-6.831', '-7.692', '1.336', '1.535', '-0.939']
Mediana val:    -0.939
Hold-out SR:    -1.235
[P5, P95]:      [-7.520, 1.495]
Cobertura:      dentro IC
  -> delta_median=0.296
[data] Observations: 410  |  Class balance: 56.3% up
[data] Feature shape: (410, 6)  |  Date range: 2018-10-01 → 2020-04-24
Synthetic 09 bull_then_crash_holdout | cpcv...

Val SRs:        ['1.654', '0.049', '1.975', '3.540', '-0.035']
Mediana val:    1.654
Hold-out SR:    3.943
[P5, P95]:      [-0.019, 3.227]
Cobertura:      fuera IC
  -> delta_median=-2.289
Synthetic 09 bull_then_crash_holdout | wf...

Val SRs:        ['-5.995', '-1.061']
Mediana val:    -3.528
Hold-out SR:    3.943
[P5, P95]:      [-5.749, -1.307]
Cobertura:      fuera IC
  -> delta_median=-7.471
Synthetic 09 bull_then_crash_holdout | kfold...

Val SRs:        ['-7.830', '2.032', '8.748', '7.281', '-2.012']
Mediana val:    2.032
Hold-out SR:    3.943
[P5, P95]:      [-6.666, 8.454]
Cobertura:      dentro IC
  -> delta_median=-1.911
[data] Observations: 410  |  Class balance: 38.8% up
[data] Feature shape: (410, 6)  |  Date range: 2018-10-01 → 2020-04-24
Synthetic 10 bear_then_recovery_holdout | cpcv...

Val SRs:        ['6.363', '8.502', '5.765', '7.851', '6.562']
Mediana val:    6.562
Hold-out SR:    1.823
[P5, P95]:      [5.884, 8.372]
Cobertura:      fuera IC
  -> delta_median=4.739
Synthetic 10 bear_then_recovery_holdout | wf...

Val SRs:        ['8.697', '5.164']
Mediana val:    6.931
Hold-out SR:    1.823
[P5, P95]:      [5.341, 8.521]
Cobertura:      fuera IC
  -> delta_median=5.108
Synthetic 10 bear_then_recovery_holdout | kfold...

Val SRs:        ['5.014', '7.317', '12.495', '5.161', '8.613']
Mediana val:    7.317
Hold-out SR:    1.823
[P5, P95]:      [5.043, 11.719]
Cobertura:      fuera IC
  -> delta_median=5.494
[data] Observations: 410  |  Class balance: 61.7% up
[data] Feature shape: (410, 6)  |  Date range: 2018-10-01 → 2020-04-24
Synthetic 11 crash_dev_recovery_holdout | cpcv...

Val SRs:        ['1.919', '4.752', '2.591', '3.520', '2.489']
Mediana val:    2.591
Hold-out SR:    6.654
[P5, P95]:      [2.033, 4.506]
Cobertura:      fuera IC
  -> delta_median=-4.063
Synthetic 11 crash_dev_recovery_holdout | wf...

Val SRs:        ['6.897', '3.572']
Mediana val:    5.234
Hold-out SR:    6.654
[P5, P95]:      [3.738, 6.731]
Cobertura:      dentro IC
  -> delta_median=-1.419
Synthetic 11 crash_dev_recovery_holdout | kfold...

Val SRs:        ['1.113', '4.980', '5.719', '1.931', '4.335']
Mediana val:    4.335
Hold-out SR:    6.654
[P5, P95]:      [1.277, 5.571]
Cobertura:      fuera IC
  -> delta_median=-2.318
[data] Observations: 410  |  Class balance: 51.5% up
[data] Feature shape: (410, 6)  |  Date range: 2018-10-01 → 2020-04-24
Synthetic 12 stagnant_crash_holdout | cpcv...

Val SRs:        ['2.742', '3.678', '2.692', '1.794', '2.367']
Mediana val:    2.692
Hold-out SR:    0.381
[P5, P95]:      [1.909, 3.491]
Cobertura:      fuera IC
  -> delta_median=2.312
Synthetic 12 stagnant_crash_holdout | wf...

Val SRs:        ['4.346', '-0.991']
Mediana val:    1.677
Hold-out SR:    0.381
[P5, P95]:      [-0.724, 4.079]
Cobertura:      dentro IC
  -> delta_median=1.297
Synthetic 12 stagnant_crash_holdout | kfold...

Val SRs:        ['8.582', '2.832', '7.759', '-2.709', '2.738']
Mediana val:    2.832
Hold-out SR:    0.381
[P5, P95]:      [-1.620, 8.418]
Cobertura:      dentro IC
  -> delta_median=2.451
[data] Observations: 410  |  Class balance: 54.6% up
[data] Feature shape: (410, 6)  |  Date range: 2018-10-01 → 2020-04-24
Synthetic 13 bull_crash_retrain_recovery | cpcv...

Val SRs:        ['-0.308', '-0.995', '-1.849', '1.338', '0.258']
Mediana val:    -0.308
Hold-out SR:    -5.358
[P5, P95]:      [-1.679, 1.122]
Cobertura:      fuera IC
  -> delta_median=5.050
Synthetic 13 bull_crash_retrain_recovery | wf...

Val SRs:        ['2.406', '-1.503']
Mediana val:    0.451
Hold-out SR:    -5.358
[P5, P95]:      [-1.308, 2.211]
Cobertura:      fuera IC
  -> delta_median=5.809
Synthetic 13 bull_crash_retrain_recovery | kfold...

Val SRs:        ['-1.708', '5.505', '1.499', '-2.066', '-3.988']
Mediana val:    -1.708
Hold-out SR:    -5.358
[P5, P95]:      [-3.604, 4.704]
Cobertura:      fuera IC
  -> delta_median=3.649
[data] Observations: 410  |  Class balance: 60.0% up
[data] Feature shape: (410, 6)  |  Date range: 2018-10-01 → 2020-04-24
Synthetic 14 double_crash_dev_holdout | cpcv...

Val SRs:        ['1.320', '3.055', '3.700', '0.897', '3.195']
Mediana val:    3.055
Hold-out SR:    -2.711
[P5, P95]:      [0.981, 3.599]
Cobertura:      fuera IC
  -> delta_median=5.767
Synthetic 14 double_crash_dev_holdout | wf...

Val SRs:        ['5.340', '6.301']
Mediana val:    5.820
Hold-out SR:    -2.711
[P5, P95]:      [5.388, 6.253]
Cobertura:      fuera IC
  -> delta_median=8.532
Synthetic 14 double_crash_dev_holdout | kfold...

Val SRs:        ['-1.483', '2.961', '0.262', '5.283', '7.019']
Mediana val:    2.961
Hold-out SR:    -2.711
[P5, P95]:      [-1.134, 6.672]
Cobertura:      fuera IC
  -> delta_median=5.672
[data] Observations: 410  |  Class balance: 58.0% up
[data] Feature shape: (410, 6)  |  Date range: 2018-10-01 → 2020-04-24
Synthetic 15 recovery_after_crash_dev | cpcv...

Val SRs:        ['-1.142', '0.570', '-1.081', '-0.647', '-1.089']
Mediana val:    -1.081
Hold-out SR:    -2.280
[P5, P95]:      [-1.131, 0.327]
Cobertura:      fuera IC
  -> delta_median=1.199
Synthetic 15 recovery_after_crash_dev | wf...

Val SRs:        ['-0.042', '-0.745']
Mediana val:    -0.394
Hold-out SR:    -2.280
[P5, P95]:      [-0.710, -0.077]
Cobertura:      fuera IC
  -> delta_median=1.887
Synthetic 15 recovery_after_crash_dev | kfold...

Val SRs:        ['3.080', '1.835', '-6.882', '-2.805', '3.533']
Mediana val:    1.835
Hold-out SR:    -2.280
[P5, P95]:      [-6.067, 3.442]
Cobertura:      dentro IC
  -> delta_median=4.115
[data] Observations: 410  |  Class balance: 49.8% up
[data] Feature shape: (410, 6)  |  Date range: 2018-10-01 → 2020-04-24
Synthetic 16 crash_start_warmup | cpcv...

Val SRs:        ['4.138', '2.738', '1.168', '2.231', '1.304']
Mediana val:    2.231
Hold-out SR:    -1.176
[P5, P95]:      [1.195, 3.858]
Cobertura:      fuera IC
  -> delta_median=3.407
Synthetic 16 crash_start_warmup | wf...

Val SRs:        ['-5.577', '-0.086']
Mediana val:    -2.832
Hold-out SR:    -1.176
[P5, P95]:      [-5.303, -0.361]
Cobertura:      dentro IC
  -> delta_median=-1.656
Synthetic 16 crash_start_warmup | kfold...

Val SRs:        ['4.183', '-2.797', '5.298', '4.608', '-3.016']
Mediana val:    4.183
Hold-out SR:    -1.176
[P5, P95]:      [-2.972, 5.160]
Cobertura:      dentro IC
  -> delta_median=5.360
[data] Observations: 410  |  Class balance: 43.4% up
[data] Feature shape: (410, 6)  |  Date range: 2018-10-01 → 2020-04-24
Synthetic 17 long_bull_short_crash_holdout | cpcv...

Val SRs:        ['0.828', '0.378', '-0.007', '-4.699', '-3.886']
Mediana val:    -0.007
Hold-out SR:    -1.288
[P5, P95]:      [-4.536, 0.738]
Cobertura:      dentro IC
  -> delta_median=1.281
Synthetic 17 long_bull_short_crash_holdout | wf...

Val SRs:        ['-4.480', '-3.370']
Mediana val:    -3.925
Hold-out SR:    -1.288
[P5, P95]:      [-4.425, -3.425]
Cobertura:      fuera IC
  -> delta_median=-2.637
Synthetic 17 long_bull_short_crash_holdout | kfold...

Val SRs:        ['-8.238', '-4.685', '-3.661', '10.263', '2.248']
Mediana val:    -3.661
Hold-out SR:    -1.288
[P5, P95]:      [-7.528, 8.660]
Cobertura:      dentro IC
  -> delta_median=-2.372
[data] Observations: 410  |  Class balance: 53.7% up
[data] Feature shape: (410, 6)  |  Date range: 2018-10-01 → 2020-04-24
Synthetic 18 volatile_bull | cpcv...

Val SRs:        ['0.070', '1.031', '0.743', '1.830', '2.121']
Mediana val:    1.031
Hold-out SR:    -0.172
[P5, P95]:      [0.205, 2.063]
Cobertura:      fuera IC
  -> delta_median=1.203
Synthetic 18 volatile_bull | wf...

Val SRs:        ['-1.768', '0.598']
Mediana val:    -0.585
Hold-out SR:    -0.172
[P5, P95]:      [-1.650, 0.479]
Cobertura:      dentro IC
  -> delta_median=-0.413
Synthetic 18 volatile_bull | kfold...

Val SRs:        ['-3.390', '-2.818', '-0.720', '2.488', '7.375']
Mediana val:    -0.720
Hold-out SR:    -0.172
[P5, P95]:      [-3.276, 6.398]
Cobertura:      dentro IC
  -> delta_median=-0.548
[data] Observations: 410  |  Class balance: 49.3% up
[data] Feature shape: (410, 6)  |  Date range: 2018-10-01 → 2020-04-24
Synthetic 19 bear_crash_recovery | cpcv...

Val SRs:        ['-3.908', '-4.982', '-3.093', '-3.724', '-2.008']
Mediana val:    -3.724
Hold-out SR:    -3.327
[P5, P95]:      [-4.767, -2.225]
Cobertura:      dentro IC
  -> delta_median=-0.396
Synthetic 19 bear_crash_recovery | wf...

Val SRs:        ['-4.337', '-2.855']
Mediana val:    -3.596
Hold-out SR:    -3.327
[P5, P95]:      [-4.263, -2.930]
Cobertura:      dentro IC
  -> delta_median=-0.269
Synthetic 19 bear_crash_recovery | kfold...

Val SRs:        ['-5.298', '-5.832', '-4.049', '-3.916', '-5.008']
Mediana val:    -5.008
Hold-out SR:    -3.327
[P5, P95]:      [-5.725, -3.943]
Cobertura:      fuera IC
  -> delta_median=-1.681
[data] Observations: 410  |  Class balance: 42.0% up
[data] Feature shape: (410, 6)  |  Date range: 2018-10-01 → 2020-04-24
Synthetic 20 realistic_covid_analog | cpcv...

Val SRs:        ['4.660', '2.378', '2.191', '4.162', '4.751']
Mediana val:    4.162
Hold-out SR:    2.095
[P5, P95]:      [2.229, 4.733]
Cobertura:      fuera IC
  -> delta_median=2.068
Synthetic 20 realistic_covid_analog | wf...

Val SRs:        ['3.296', '-0.462']
Mediana val:    1.417
Hold-out SR:    2.095
[P5, P95]:      [-0.274, 3.108]
Cobertura:      dentro IC
  -> delta_median=-0.677
Synthetic 20 realistic_covid_analog | kfold...

Val SRs:        ['2.903', '3.639', '12.788', '-0.303', '3.055']
Mediana val:    3.055
Hold-out SR:    2.095
[P5, P95]:      [0.338, 10.958]
Cobertura:      dentro IC
  -> delta_median=0.961

Completed 60 synthetic experiments

In [5]:
display_cols2 = ["scenario_id", "scenario_name", "method",
                 "delta_median", "coverage_90", "rank_pct",
                 "dispersion", "delta_maxDD", "pct_positive"]
synth_df[display_cols2].round(4)

,scenario_id,scenario_name,method,delta_median,coverage_90,rank_pct,dispersion,delta_maxDD,pct_positive
0,01,bull_bull_bull,cpcv,9.3868,0,0.0,0.8241,0.2291,1.0
1,01,bull_bull_bull,wf,7.9243,0,0.0,3.4493,0.1809,0.5
2,01,bull_bull_bull,kfold,6.9407,0,0.0,5.2340,0.2131,0.8
3,02,bear_bear_bear,cpcv,-0.4843,1,0.8,1.2442,0.0004,0.6
4,02,bear_bear_bear,wf,-0.8670,0,1.0,0.0100,-0.0322,1.0
5,02,bear_bear_bear,kfold,-1.9604,1,0.6,4.5508,-0.3790,0.4
6,03,stagnant_all,cpcv,-2.6225,0,1.0,1.1418,-0.1043,0.4
7,03,stagnant_all,wf,-3.4472,0,1.0,1.8755,-0.2401,0.5
8,03,stagnant_all,kfold,-3.4137,1,0.8,4.6747,-0.2895,0.4
9,04,crash_in_dev_start,cpcv,8.1012,0,0.0,0.5126,0.2314,1.0
10,04,crash_in_dev_start,wf,8.7102,0,0.0,2.8264,0.2400,1.0
11,04,crash_in_dev_start,kfold,9.0465,0,0.0,2.9618,0.2400,1.0
12,05,crash_in_dev_end,cpcv,2.5191,0,0.0,0.7026,-0.5857,0.0
13,05,crash_in_dev_end,wf,0.9735,1,0.5,4.3955,-0.2816,0.5
14,05,crash_in_dev_end,kfold,4.1424,1,0.2,10.9665,-1.0444,0.6
15,06,crash_in_retrain,cpcv,-4.0548,0,1.0,0.8015,-0.6656,0.0
16,06,crash_in_retrain,wf,-1.8522,0,1.0,0.1762,-0.4587,1.0
17,06,crash_in_retrain,kfold,-0.8663,0,1.0,2.3266,-0.2952,0.6
18,07,crash_in_holdout_start,cpcv,0.2718,1,0.4,1.9631,0.2296,0.2
19,07,crash_in_holdout_start,wf,2.7629,0,0.0,0.0510,0.3396,1.0
20,07,crash_in_holdout_start,kfold,-1.7513,0,1.0,1.7739,-0.0133,0.0
21,08,crash_in_holdout_end,cpcv,0.1111,1,0.2,0.7673,0.2646,0.2
22,08,crash_in_holdout_end,wf,4.1522,0,0.0,2.0030,0.3585,1.0
23,08,crash_in_holdout_end,kfold,0.2958,1,0.4,3.9786,0.0575,0.4
24,09,bull_then_crash_holdout,cpcv,-2.2894,0,1.0,1.3308,0.1977,0.8
25,09,bull_then_crash_holdout,wf,-7.4710,0,1.0,2.4673,-0.3185,0.0
26,09,bull_then_crash_holdout,kfold,-1.9106,1,0.6,6.0911,0.0370,0.6
27,10,bear_then_recovery_holdout,cpcv,4.7392,0,0.0,1.0102,0.1466,1.0
28,10,bear_then_recovery_holdout,wf,5.1079,0,0.0,1.7667,0.0388,1.0
29,10,bear_then_recovery_holdout,kfold,5.4940,0,0.0,2.7435,0.0388,1.0
30,11,crash_dev_recovery_holdout,cpcv,-4.0629,0,1.0,0.9923,-0.1378,1.0
31,11,crash_dev_recovery_holdout,wf,-1.4192,1,0.5,1.6627,-0.0656,1.0
32,11,crash_dev_recovery_holdout,kfold,-2.3184,0,1.0,1.7833,-0.1651,1.0
33,12,stagnant_crash_holdout,cpcv,2.3116,0,0.0,0.6131,0.5253,1.0
34,12,stagnant_crash_holdout,wf,1.2966,1,0.5,2.6685,0.4035,0.5
35,12,stagnant_crash_holdout,kfold,2.4512,1,0.2,4.0737,0.4836,0.8
36,13,bull_crash_retrain_recovery,cpcv,5.0500,0,0.0,1.0841,-0.1727,0.4
37,13,bull_crash_retrain_recovery,wf,5.8091,0,0.0,1.9547,-0.1797,0.5
38,13,bull_crash_retrain_recovery,kfold,3.6494,0,0.0,3.3328,-0.1172,0.4
39,14,double_crash_dev_holdout,cpcv,5.7666,0,0.0,1.1110,0.3864,1.0
40,14,double_crash_dev_holdout,wf,8.5316,0,0.0,0.4803,0.5924,1.0
41,14,double_crash_dev_holdout,kfold,5.6724,0,0.0,3.1231,0.3959,0.8
42,15,recovery_after_crash_dev,cpcv,1.1994,0,0.0,0.6489,-1.3104,0.2
43,15,recovery_after_crash_dev,wf,1.8868,0,0.0,0.3519,-0.9795,0.0
44,15,recovery_after_crash_dev,kfold,4.1152,1,0.4,4.0065,-1.4998,0.6
45,16,crash_start_warmup,cpcv,3.4073,0,0.0,1.0813,-0.0479,1.0
46,16,crash_start_warmup,wf,-1.6557,1,0.5,2.7455,-0.5022,0.0
47,16,crash_start_warmup,kfold,5.3596,1,0.4,3.7424,-0.1725,0.6
48,17,long_bull_short_crash_holdout,cpcv,1.2813,1,0.4,2.3282,0.8276,0.4
49,17,long_bull_short_crash_holdout,wf,-2.6367,0,1.0,0.5554,0.7361,0.0
50,17,long_bull_short_crash_holdout,kfold,-2.3723,1,0.6,6.4852,0.7385,0.4
51,18,volatile_bull,cpcv,1.2028,0,0.0,0.7417,0.0500,1.0
52,18,volatile_bull,wf,-0.4130,1,0.5,1.1827,-0.0436,0.5
53,18,volatile_bull,kfold,-0.5482,1,0.6,3.9705,-0.0086,0.4
54,19,bear_crash_recovery,cpcv,-0.3964,1,0.6,0.9791,-1.8710,0.0
55,19,bear_crash_recovery,wf,-0.2691,1,0.5,0.7409,-1.6532,0.0
56,19,bear_crash_recovery,kfold,-1.6807,0,1.0,0.7346,-2.2507,0.0
57,20,realistic_covid_analog,cpcv,2.0678,0,0.0,1.1170,0.4831,1.0
58,20,realistic_covid_analog,wf,-0.6774,1,0.5,1.8793,0.4759,0.5
59,20,realistic_covid_analog,kfold,0.9608,1,0.2,4.4069,0.4521,0.8

In [6]:
agg_cols = ["delta_median", "coverage_90", "rank_pct", "dispersion", "delta_maxDD", "pct_positive"]
summary_df = synth_df.groupby("method")[agg_cols].mean().round(4)
summary_df.index.name = "method"
summary_df.to_csv("results/summary_by_method.csv")

print("=== TABLE 3: Average calibration metrics per method (60 synthetic runs) ===")
display(summary_df)

=== TABLE 3: Average calibration metrics per method (60 synthetic runs) ===

,delta_median,coverage_90,rank_pct,dispersion,delta_maxDD,pct_positive
method,,,,,,
cpcv,1.6753,0.25,0.320,1.0498,-0.0662,0.610
kfold,1.5653,0.55,0.450,4.0480,-0.1789,0.580
wf,1.3223,0.35,0.425,1.6622,-0.0695,0.575

In [7]:
print(f"Real experiments: {len(real_df)} rows (expected 24)")
print(f"Synthetic experiments: {len(synth_df)} rows (expected 60)")
import glob
n_plots = len(glob.glob("plots/*.png"))
print(f"Figures saved: {n_plots} (expected 84)")
print(f"CSVs in results/: {os.listdir('results/')}")

assert len(real_df) == 24, f"Expected 24 real rows, got {len(real_df)}"
assert len(synth_df) == 60, f"Expected 60 synthetic rows, got {len(synth_df)}"
print("All assertions passed.")

Real experiments: 24 rows (expected 24)
Synthetic experiments: 60 rows (expected 60)
Figures saved: 89 (expected 84)
CSVs in results/: ['synthetic_experiments.csv', 'summary_by_method.csv', 'real_experiments.csv']
All assertions passed.